server:
    port: 8080
    address: localhost

spring:
    profiles: dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: 
        databaseName: travelApp
        serverName: localhost
        username: travelApp
        password:

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: de.kmapper.web
      domain: de.kmapper.web.domain
      restdto: de.kmapper.web.web.rest.dto
    liquibase:
      defaultCatalogName: 
      defaultSchema: public
    watchdir:
      - target/classes
